Feat  add search component
Taras-js/dupedex-project pull request #11
Opened 2022-04-24 10:33 UTC by Sultan06-lab

2022-04-24 13:39 UTC, martinLjs requested changes

2022-04-24 13:39 UTC, martinLjs commented on client/src/app/store.ts
> +    reducer: { counter: counterReducer, product: productReducer },
products лучше, их ведь много

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/ProductSearch.tsx
> +  const result = useAppSelector((state) => state.product);
лучше тогда products = ... => state.product.products

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/ProductSearch.tsx
> +  const result = useAppSelector((state) => state.product);
можно сделать селектор отдельный, спроси если непонятно будет как сделать

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.module.css
> +.main__input {
возможно лучше search__input чтобы потом в классы легко искать когда проект больше станет main абстрактно

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +export interface Results {
search переиспользуемый компонент, возможно будет какой нибудь поиск по юзерам, тогда эти типы будут ни к чему. лучше сделать title, subtitle для results(в будущем и image будет)

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +export interface SearchProps {
а если захотим передать начальное значение поиска?

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +  const debounce = (func) => {
это надо вынести в отдельный shared/helper.js. И зачем он в search? для product мы делаем затратные запросы на сервер, а для какого нибудь поиска по списку debouncing не нужен, вынеси его в product search

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +  const optomizedVersion = useCallback(debounce(onChange), []);
не лучшее название для переменной.

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +  const debounce = (func) => {
Как вариант добавить кстати в Search prop withDebouncing которое обернет onChange в дебаунсинг

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/searchProductAction.ts
> +export const searchProduct = (search: string) => (dispatch: AppDispatch) => {
какой то странный action

2022-04-24 13:39 UTC, martinLjs commented on client/src/pages/index.tsx
> +          <ProductSearch />
поиск у меня пока не сработал.

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/ProductSearch.tsx
> +  const result = useAppSelector((state) => state.product);
мы должны хранить все продукты полученные с базы в products, для кеша так сказать. Поэтому вместо этого (state) => state.product , создай отдельную функцию getProductsBySearch которая принимает строку и и достает подходящие товары из product reducer. можно создать тут файл SearchSelector.ts

2022-04-24 13:39 UTC, martinLjs commented on client/src/features/Search/Search.tsx
> +import React, { useCallback } from 'react';
feature/ProductSearch папка, а Search.tsx и его стили отдельно в UIKit уточни у максима про эту папку

2022-04-28 10:44 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.module.css
> +}
Мне кажется, здесь можно добавить width: 100%, или сверху допклассом прокидывать, чтобы компонент все пространство занимал

2022-04-28 10:44 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.module.css
> +}
Нужно добавить, dropdown такое свойство имеет, и они могут по размеру не совпадать

2022-04-28 10:44 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +  placeholder, onChange, results, withDebounce,
Наверное, лучше внутри функции уже сделать декомпозицию {} = props. Если что-то добавить нужно будем, здесь много городить

2022-04-28 10:44 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +  const optomizedVersion = useCallback(withDebounce(onChange), []);
optimized

2022-04-28 10:44 UTC, Antreesy commented on client/src/features/Search/ProductSearch.tsx
> +      withDebounce={debounce}
Тут вряд ли будут другие варианты. Нельзя вместо пропса сразу внутри Search обернуть debounce(onChange())?

2022-04-28 10:44 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +            <p className={styles.search__brand_name}>{ `- ${result.brand_name}`}</p>
На первом месте в макете brand_name, на втором - product_name

2022-04-28 11:12 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +  prod_name?: string;
Нужно будет добавить получение id

2022-04-28 11:13 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +          <div className={styles.search__item}>
а div лучше сразу поменяй на button, потом на неё повесим сразу экшн

2022-04-28 14:14 UTC, martinLjs requested changes

2022-04-28 14:14 UTC, martinLjs commented on client/src/components/UIKit/Search/Search.tsx
> +  prod_name?: string;
да блин, что за prod_name, brand_name - это ведь переиспользуемый компонент, у него есть заголовок, подзаголовок (потом будет и img).  мы потом добавим  value в results и в props потом уже добавим onResultClick

так что это надо вернуть

2022-04-28 14:14 UTC, martinLjs commented on client/src/components/UIKit/Search/Search.tsx
> +          <div className={styles.search__item}>
аналогично комментарию выше

2022-04-28 14:14 UTC, martinLjs commented on client/src/features/counter/Counter.module.css
> -  composes: button;
для чего это?

2022-04-29 09:16 UTC, Antreesy commented on client/src/components/UIKit/Search/ResultItem.tsx
> +  return (
Нужен handleClick, который обрабатывает onClick из пропсов.
попробуй передать в него dispatch(getItem(id))

2022-04-29 09:20 UTC, Antreesy commented on client/src/features/Search/SearchSelector.ts
> +  search.length > 1 && (state.filter((product) => (product.prod_name).toString().toLowerCase().includes(search.toLowerCase()))).map((product) => ({
Нужен еще поиск по названию брэнда, попробуй добавить 
(product.prod_name).toString().toLowerCase().includes(search.toLowerCase()) || (product.brand_name).toString().toLowerCase().includes(search.toLowerCase())

2022-04-29 09:23 UTC, Antreesy commented on client/src/app/store.ts
> +import goodsReducer from '../features/Search/productSlice';
Двойные, чтобы prettier потом не исправлял

2022-04-29 09:24 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +  const optomized = useCallback(withDebounce(onChange), []);
optimized

2022-04-29 09:24 UTC, Antreesy commented on client/src/components/UIKit/Search/Search.tsx
> +          onChange={optomized}
optimized

2022-05-01 12:09 UTC, merged