Feat: add products
Taras-js/dupedex-project pull request #8
Opened 2022-04-20 16:53 UTC by Antreesy

2022-04-20 22:07 UTC, martinLjs reviewed
Задачу надо обсудить, пока не делать

2022-04-20 22:07 UTC, martinLjs commented on client/src/pages/index.tsx
> +        {productsMock.map((item) => (
для 1-2 продуктов отображается не совсем верно. кейс с текстовым отзывом не отработан, надо обсудить.

2022-04-21 06:51 UTC, martinLjs commented on client/src/interfaces/ProductProps.tsx
> +}
я думаю лучше писать интерфейсы props в компоненте, а общие props в shared/types.ts

2022-04-21 13:39 UTC, Antreesy commented on client/src/components/ProductItem/ProductItem.tsx
> +/* eslint-disable react/destructuring-assignment */
Это в любом случае заглушка, пока нормальный компонент не проработаем

2022-04-22 07:47 UTC, martinLjs requested changes

2022-04-22 07:47 UTC, martinLjs commented on client/src/components/ProductComponent/ProductComponent.tsx
> +  isReviewShow? : boolean;
isReviewShown
судя по тому, что productList будет в виде селектора а не props, нам и isReviewShown нужно хранить как константу мок пока (потом заменим на useSelector)

2022-04-22 07:47 UTC, martinLjs commented on client/src/components/UIKit/Panel/Panel.tsx
> +const Panel = (props: PanelProps) => {
const Panel: React.FC<PanelProps> = (props) => {
поэтому сейчас ошибки типов с key, children

2022-04-22 07:47 UTC, martinLjs commented on client/src/components/ProductComponent/ProductComponent.tsx
> +  if (productList.length === 1) {
Это общий комментарий по ProductComponent . Текущая реализация не соответсвует нашей ориентировочной структуре.
**products**
products: [{*product object*}]

**content**
items: [id1, id3, …]
textReview: id | null,

Так что при добавлении логики структура сильно поменяется, это не очень хорошо.

Лучше тогда убрать для productComponent пропсы
Использовать две моковые константы(потом будут селекторами)
productIds, review и они уже соответсвенно будут использоваться:
productIds.map...
review && <Review .../>(пока можно не выносить в отдельный компонент)

2022-04-22 07:47 UTC, martinLjs commented on client/src/components/ProductComponent/ProductComponent.tsx
> +const ProductComponent = (props: ProductProps) => {
Лучше ProductContainer

2022-04-22 07:47 UTC, martinLjs commented on client/src/components/ProductComponent/ProductComponent.tsx
> +const ProductComponent = (props: ProductProps) => {
Типизация должна быть как в моем примере с Panel

2022-04-24 13:16 UTC, martinLjs approved these changes

2022-04-24 13:16 UTC, martinLjs commented on client/src/shared/types/types.ts
> +export type FilterType = 'positive' | 'neutral' | 'negative' | null;
можно использовать enum

2022-04-24 13:19 UTC, merged